project:
  type: website

website:
  title: "Teste de website"
  navbar:
    left:
      - href: index.qmd
        text: Hahah
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

output-dir: _site