project:
  type: website

website:
  title: "Projeto Ferramentas de Produtividade"
  navbar:
    left:
      - href: index.qmd
        text: Página inicial
      - href: currículo.qmd
        text: Currículo
      - href: projetos.qmd
        text: Projetos
      - href: contacto.qmd
        text: Contacto
      - href: imagem.qmd
        text: Imagem

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

output-dir: _site