project:
  type: website

website:
  title: "Teste de website do Blober"
  navbar:
    left:
      - href: index.qmd
        text: Please
      - href: about.qmd
        text: work goddam

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

output-dir: _site